version: '3'
services:
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management-alpine
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "80:15672"
      - "5672:5672" 
    networks:
      - log
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: EnterpriseLog

volumes:
  mq_data:

networks:
  log:
    driver: bridge